# Generated by Django 4.1.6 on 2023-02-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='operation_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Приход'), (2, 'Возврат прихода'), (3, 'Расход'), (4, 'Возврат расхода')], null=True),
        ),
    ]
