# Generated by Django 4.1.6 on 2023-02-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_receipt_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nds_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
