# Generated by Django 4.2.3 on 2023-07-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='retail_place',
            field=models.CharField(
                blank=True, default='Нет данных', max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name='customer',
            name='retail_place_address',
            field=models.CharField(
                blank=True, default='Нет данных', max_length=1000
            ),
        ),
    ]
