# Generated by Django 4.2.3 on 2023-07-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_alter_customer_retail_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='manual',
            field=models.BooleanField(null=True),
        ),
    ]
