# Generated by Django 4.2.2 on 2023-06-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_alter_customer_user_alter_product_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='receipts.customer', verbose_name='customer'),
        ),
    ]
