# Generated by Django 4.1.7 on 2023-02-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
