# Generated by Django 4.1.7 on 2023-03-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name_seller',
            field=models.CharField(max_length=255),
        ),
    ]
