# Generated by Django 4.2.4 on 2023-09-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0006_alter_receipt_operation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="nds_10",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=60, null=True,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="nds_20",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=60, null=True,
            ),
        ),
    ]
