# Generated by Django 4.1.7 on 2023-03-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_alter_customer_name_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='number_receipt',
            field=models.IntegerField(null=True),
        ),
    ]
