# Generated by Django 4.2.4 on 2023-09-04 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0007_receipt_nds_10_receipt_nds_20"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="nds_10",
            new_name="nds10",
        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="nds_20",
            new_name="nds20",
        ),
    ]
