# Generated by Django 4.2.1 on 2023-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_receipt_number_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='retail_place',
            field=models.CharField(blank=True, default='Нет данных', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='retail_place_address',
            field=models.CharField(default='Нет данных', max_length=1000, null=True),
        ),
    ]
