# Generated by Django 4.2.1 on 2023-05-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_alter_customer_retail_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='nds_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nds_type',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Нет данных', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='number_receipt',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='operation_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Приход'), (2, 'Возврат прихода'), (3, 'Расход'), (4, 'Возврат расхода')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
