# Generated by Django 4.2.5 on 2023-09-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0009_alter_receipt_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["-receipt_date"], name="receipts_re_receipt_27a810_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["number_receipt"], name="receipts_re_number__8b0553_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["nds10"], name="receipts_re_nds10_eca936_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["nds20"], name="receipts_re_nds20_70a9e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["operation_type"], name="receipts_re_operati_6c2387_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["total_sum"], name="receipts_re_total_s_b77e3b_idx"
            ),
        ),
    ]
