# Generated by Django 4.2.13 on 2024-05-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0018_delete_fileupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="category",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
