# Generated by Django 4.2.13 on 2024-05-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0019_receipt_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
