# Generated by Django 4.2.16 on 2024-09-23 21:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts', '0020_remove_receipt_category_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Seller',
        ),
    ]
