# Generated by Django 4.2.16 on 2024-09-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0021_rename_customer_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='customer',
            new_name='seller',
        ),
    ]
