# Generated by Django 4.2.1 on 2023-06-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('category', models.CharField(choices=[('ЖКХ', 'ЖКХ')], max_length=20)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
