# Generated by Django 4.2.1 on 2023-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ЖКХ', 'ЖКХ')], max_length=10),
        ),
    ]
