# Generated by Django 4.2.5 on 2023-09-20 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="expensetype",
            options={"ordering": ["name"]},
        ),
    ]
