# Generated by Django 4.2.1 on 2023-06-13 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_alter_account_user'),
        ('expense', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
