# Generated by Django 4.2.5 on 2023-09-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0003_alter_expense_options_alter_expensetype_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["-date"], name="expense_exp_date_5e5d86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["amount"], name="expense_exp_amount_ce8d33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expensetype",
            index=models.Index(
                fields=["name"], name="expense_exp_name_56543f_idx"
            ),
        ),
    ]
