# Generated by Django 4.2.2 on 2023-06-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_expense_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
    ]
