# Generated by Django 4.2.7 on 2023-12-05 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0016_parentcategoryexpense_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expensecategory",
            name="parent_category_self",
        ),
        migrations.DeleteModel(
            name="ParentCategoryExpense",
        ),
    ]
