# Generated by Django 4.2.7 on 2023-12-04 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0017_alter_expensecategory_parent_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expensecategory",
            name="parent_category_self",
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="expense.expensecategory",
            ),
        ),
        migrations.DeleteModel(
            name="ParentCategoryExpense",
        ),
    ]
