# Generated by Django 4.0.4 on 2022-05-04 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password2',
        ),
    ]
