# Generated by Django 4.0.4 on 2022-05-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0004_useradmin_delete_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAdmin',
            new_name='User',
        ),
    ]
