# Generated by Django 4.0.4 on 2022-05-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.CharField(max_length=20)),
                ('name_seller', models.CharField(max_length=150)),
                ('product_information', models.CharField(max_length=1000)),
                ('total_sum', models.CharField(max_length=20)),
            ],
        ),
    ]
