# Generated by Django 4.0.4 on 2022-05-18 21:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.CharField(max_length=20)),
                ('name_seller', models.CharField(max_length=150)),
                ('product_information', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None), size=None)),
                ('total_sum', models.CharField(max_length=20)),
            ],
        ),
    ]
