# Generated by Django 4.0.4 on 2022-05-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateTimeField(max_length=20),
        ),
    ]
