# Generated by Django 4.0.4 on 2022-05-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipts',
        ),
    ]
