# Generated by Django 4.0.4 on 2022-06-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_receipt_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateTimeField(),
        ),
    ]
