# Generated by Django 4.0.6 on 2022-08-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_alter_receipt_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='nds_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='operation_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='product_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='retail_place',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='retail_place_address',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
