# Generated by Django 4.2.10 on 2024-04-09 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0006_alter_datelist_user_alter_planning_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datelist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_date_list_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="planning",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_category_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
