# Generated by Django 4.2.4 on 2023-08-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_verify",
        ),
        migrations.AlterField(
            model_name="user",
            name="policy",
            field=models.BooleanField(null=True, unique=True),
        ),
    ]
