# Generated by Django 4.2.2 on 2023-06-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_user'),
        ('users', '0006_remove_telegramuser_selected_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='selected_account_id',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='selected_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account'),
        ),
    ]
