# Generated by Django 4.2.4 on 2023-08-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_user_email_verify_alter_user_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="policy",
            field=models.BooleanField(null=True),
        ),
    ]
