# Generated by Django 4.2.10 on 2024-03-18 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0019_alter_account_currency_alter_transfermoneylog_notes"),
        ("income", "0021_alter_incomecategory_parent_category"),
        ("expense", "0018_alter_expensecategory_parent_category"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("loan", "0020_loan_type_loan"),
        ("receipts", "0012_alter_product_quantity"),
        ("budget", "0001_initial"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("users", "0008_remove_user_policy_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="CustomUser",
        ),
    ]
