# Generated by Django 4.0.4 on 2022-05-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_receipts_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
