# Generated by Django 4.2.2 on 2023-06-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_transfermoneylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermoneylog',
            name='exchange_date',
            field=models.DateTimeField(),
        ),
    ]
