# Generated by Django 4.2.2 on 2023-06-30 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_alter_transfermoneylog_exchange_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermoneylog',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='account.account'),
        ),
        migrations.AlterField(
            model_name='transfermoneylog',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='account.account'),
        ),
        migrations.AlterField(
            model_name='transfermoneylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
