# Generated by Django 4.2.5 on 2023-09-20 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_transfermoneylog_from_account_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["name_account"]},
        ),
    ]
