# Generated by Django 4.2.6 on 2023-10-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0011_alter_transfermoneylog_options_alter_account_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transfermoneylog",
            name="notes",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
