# Generated by Django 4.2.6 on 2023-10-21 23:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0012_transfermoneylog_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transfermoneylog",
            old_name="notes",
            new_name="note",
        ),
    ]
