# Generated by Django 4.2.6 on 2023-11-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0013_rename_notes_transfermoneylog_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfermoneylog",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
