# Generated by Django 4.2.6 on 2023-11-01 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0014_alter_transfermoneylog_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transfermoneylog",
            old_name="note",
            new_name="notes",
        ),
    ]
