# Generated by Django 4.2.7 on 2023-11-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0015_rename_note_transfermoneylog_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfermoneylog",
            name="exchange_date",
            field=models.DateTimeField(),
        ),
    ]
