# Generated by Django 4.2.7 on 2023-11-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0016_alter_transfermoneylog_exchange_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfermoneylog",
            name="notes",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
