# Generated by Django 4.2.7 on 2023-11-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0017_alter_transfermoneylog_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfermoneylog",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
