# Generated by Django 4.2.4 on 2023-09-04 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Loan",
        ),
    ]
