# Generated by Django 4.2.4 on 2023-09-15 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0005_paymentmakeloan_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentMakeLoan",
        ),
    ]
