# Generated by Django 4.2.4 on 2023-09-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0007_paymentmakeloan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="period_loan",
            field=models.IntegerField(),
        ),
    ]
