# Generated by Django 4.2.5 on 2023-09-20 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0008_alter_loan_period_loan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmakeloan",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_make",
                to="loan.loan",
            ),
        ),
    ]
