# Generated by Django 4.2.5 on 2023-09-25 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loan", "0010_alter_paymentmakeloan_loan"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, max_digits=60),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, max_digits=60),
                ),
                (
                    "interest",
                    models.DecimalField(decimal_places=2, max_digits=60),
                ),
                (
                    "principal_payment",
                    models.DecimalField(decimal_places=2, max_digits=60),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="loan",
            options={"ordering": ["-date"]},
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["-date"], name="loan_loan_date_cd9119_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["loan_amount"], name="loan_loan_loan_am_4dd1a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["annual_interest_rate"],
                name="loan_loan_annual__c669ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["period_loan"], name="loan_loan_period__f18127_idx"
            ),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="loan.loan"
            ),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
