# Generated by Django 4.2.5 on 2023-10-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0013_alter_paymentmakeloan_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentschedule",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="loan.loan"
            ),
        ),
    ]
