# Generated by Django 4.2.5 on 2023-10-01 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_account_account_acc_name_ac_e74e62_idx"),
        ("loan", "0014_alter_paymentschedule_loan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account.account",
            ),
        ),
    ]
