# Generated by Django 4.2.5 on 2023-10-02 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0016_alter_loan_account"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentSchedule",
        ),
    ]
