# Generated by Django 4.2.5 on 2023-10-02 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loan", "0017_delete_paymentschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, max_digits=60),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, max_digits=60),
                ),
                (
                    "interest",
                    models.DecimalField(decimal_places=2, max_digits=60),
                ),
                (
                    "principal_payment",
                    models.DecimalField(decimal_places=2, max_digits=60),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loan.loan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
