# Generated by Django 4.2.6 on 2023-10-15 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "account",
            "0011_alter_transfermoneylog_options_alter_account_user_and_more",
        ),
        ("loan", "0018_paymentschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_accounts",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmakeloan",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_make_loan_accounts",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmakeloan",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="loan.loan",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmakeloan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_make_loan_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymentschedule",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_schedule_loans",
                to="loan.loan",
            ),
        ),
        migrations.AlterField(
            model_name="paymentschedule",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_schedule_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
