# Generated by Django 4.1.6 on 2023-02-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.CharField(choices=[('Месяц', 'Месяц'), ('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Месяц'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='type_income',
            field=models.CharField(choices=[('Зарплата', 'Зарплата')], max_length=10),
        ),
    ]
