# Generated by Django 4.1.6 on 2023-02-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_month_alter_income_type_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Месяц'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=10),
        ),
    ]
