# Generated by Django 4.2.5 on 2023-09-20 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="income",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="incometype",
            options={"ordering": ["name"]},
        ),
    ]
