# Generated by Django 4.2.1 on 2023-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='type_income',
            field=models.CharField(choices=[('Зарплата', 'Зарплата')], max_length=10),
        ),
    ]
