# Generated by Django 4.1.7 on 2023-02-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_income_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.CharField(choices=[('Январь 2023', 'Январь 2023'), ('Февраль', 'Февраль 2023'), ('Март', 'Март 2023'), ('Апрель', 'Апрель 2023'), ('Май', 'Май 2023'), ('Июнь', 'Июнь 2023'), ('Июль', 'Июль 2023'), ('Август', 'Август 2023'), ('Сентябрь', 'Сентябрь 2023'), ('Октябрь', 'Месяц 2023'), ('Ноябрь', 'Ноябрь 2023'), ('Декабрь', 'Декабрь 2023')], max_length=20),
        ),
    ]
