# Generated by Django 4.2.7 on 2023-11-12 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0012_category_parent_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent_category",
        ),
    ]
