# Generated by Django 4.2.7 on 2023-11-12 17:56

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0017_incomecategory_parent_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incomecategory",
            options={"ordering": ["tree_id", "level", "name"]},
        ),
        migrations.AddField(
            model_name="incomecategory",
            name="level",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incomecategory",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incomecategory",
            name="rght",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incomecategory",
            name="tree_id",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="incomecategory",
            name="parent_category",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="income.incomecategory",
            ),
        ),
    ]
