# Generated by Django 4.2.7 on 2023-11-12 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0017_incomecategory_parent_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incomecategory",
            name="parent_category",
        ),
    ]
