# Generated by Django 4.2.7 on 2023-11-12 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "income",
            "0018_alter_incomecategory_options_incomecategory_level_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incomecategory",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="incomecategory",
            old_name="parent_category",
            new_name="parent",
        ),
    ]
