# Generated by Django 4.2.7 on 2023-11-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0018_remove_incomecategory_parent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomecategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="income.incomecategory",
            ),
        ),
    ]
