# Generated by Django 4.2.7 on 2023-11-12 20:47

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0019_alter_incomecategory_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incomecategory",
            name="parent",
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="income_categories",
                to="income.incomecategory",
            ),
        ),
    ]
